url: "https://softreset.dev"
baseurl: ""
title: "Soft Reset"

author:
  name: Michael Gilchrist
  email: michael@softreset.dev

plugins: [jekyll-paginate]
paginate: 3
paginate_path: page:num/

staticman_url: https://api.staticman.net/v3/entry/github/michaelgilch/michaelgilch.github.io/master/comments