url: "https://softreset.dev"
baseurl: ""
title: "Soft Reset"

author:
  name: Michael Gilchrist
  email: michael@softreset.dev

plugins:
  - jekyll-paginate
  - jekyll-feed
paginate: 3
paginate_path: page:num/

staticman_url: https://softreset-comments.herokuapp.com/v2/entry/michaelgilch/michaelgilch.github.io/master/comments

reCaptcha:
  siteKey: "6LdbXrAaAAAAAC2Ix9D8_7_J0ulWguX6IfTh1sMh"
  secret: "WNPGFfuumG0GAnu3rKYk0LxKvuLomyLCvhAc4iSDaugc3pip+iIh3BFMGbroLksR3cZypOhmKEHjrHCq+idvDnHjvzaUmgwrzBrU0qtQqt73HX1/lp2Js7GjUOCibQRQ2zX8JAKP5g2C3uzA6YmrJAk5YXsl++7VP/Z8mAFur5ZywSvGwkQ/yrrIQum4275vLf9rGPtk5z92r6T+695BOlcVu6xP2P+DffMwB87nFPWbylcQWxhC+/V2GXiOJCbKxyVpF8ppkl0I2nh0+SJd6bMJ5kEqhs634/+gI4ki/dyUQ6S6FCHB6Y3gjDdAqlbYDqQwQ/DY5oVcEuztn6NsszrSgVwNlg304AKC2hl8PWRKd0yu9VAsmW8Cy4K+XTZWiqBgu2hfCttaAO88wL1QZ3Iwzb+/srU9OjcbFxUFg526q6FvUnoS4r1kjeFJOjaSUflIV8W9674ZapILenifAwywbDC14jl+oy9NOtAswsushR7g5zdbOKd2ifutsirslrBb3mvNBqpldEO+YVzdvoQCCXiYX/1j0tb3tlMmYLK/38b2fqBBSFXDbw8rC/RpUPGgH+ABJQK9fC8XxVnc74rZGvbf+4YomJhtLchN+mnG8fjBzOYaiQb7aZeHt6Jat72kkIWSQOw4ii51I5hncffYejGFPUAAzo/sstRig/Q="
